spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/newbuildermall?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: buildermall
    password: 18KS62sd
    driver-class-name: com.mysql.cj.jdbc.Driver

host_name: http://www.buildermall.com/admin/
web_host_name: http://www.buildermall.com/web/

#文件上傳下載
file:
  directory:
    temporary: /var/lib/tomcat8/webapps/bm_upload/temporary/product_Image/  #临时文件存放目录
    image: /var/lib/tomcat8/webapps/bm_upload/product_Image/  #图片存放目录
    video: /var/lib/tomcat8/webapps/bm_upload/product_Video/ #影片存放目录
    contents: /var/lib/tomcat8/webapps/bm_upload/product_contents/ #产品目录存放目录
    specifications: /var/lib/tomcat8/webapps/bm_upload/product_Specifications/ #产品规格存放目录
    pdf: /var/lib/tomcat8/webapps/bm_upload/product_Pdf/       #pdf存放目录
    uploadPathLayedit: /var/lib/tomcat8/webapps/bm_upload/layedit/       #產品編輯器資源存放目录
    evaluation:  /var/lib/tomcat8/webapps/bm_upload/product_evaluation/ #产品评价存放目录